[[columns]]
name = "To do"
limit = 7
cards = [
      "/home/jesse/work/hammock/.kanban/cards/planning.md",
      ]

[[columns]]
name = "In progress"
limit = 1
cards = [
      "/home/jesse/work/hammock/.kanban/cards/kanban.md",
      ]

[[columns]]
name = "Done"
display = 10
sort_by = "last_moved_at"
sort_order = "desc"
cards = []