[[columns]]
name = "To do"
limit = 7
cards = ["/home/jesse/work/hammock/.kanban/cards/edit_card.md", "/home/jesse/work/hammock/.kanban/cards/metrics.md", "/home/jesse/work/hammock/.kanban/cards/hammock_as_saas_company.md", "/home/jesse/work/hammock/.kanban/cards/move_cards.md", "/home/jesse/work/hammock/.kanban/cards/manual_edits_of_files_should_never_break_the_system.md", "/home/jesse/work/hammock/.kanban/cards/dump_box.md", "/home/jesse/work/hammock/.kanban/cards/summarize_current_workspace_by_default.md", "/home/jesse/work/hammock/.kanban/cards/hmm_init.md", "/home/jesse/work/hammock/.kanban/cards/card_transitions.md", "/home/jesse/work/hammock/.kanban/cards/notes_tui.md", "/home/jesse/work/hammock/.kanban/cards/planning.md", "/home/jesse/work/hammock/.kanban/cards/design_herd_style_commands.md", "/home/jesse/work/hammock/.kanban/cards/add_new_cards_to_board.md"]

[[columns]]
name = "In progress"
limit = 1
cards = ["/home/jesse/work/hammock/.kanban/cards/kanban.md"]

[[columns]]
name = "Done"
display = 10
sort_by = "last_moved_at"
sort_order = "desc"
cards = []
